osx_image: xcode8.3

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os: osx

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - libsecret-1-0

install:
  - yarn

script:
  - yarn dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
      - "/^v\\d+\\.\\d+\\.\\d+$/"
